### ISSUE TITLE
Documentation addition

### ISSUE THREAD

**Issue by dragon-ball6** [99TheDark/Dark.js#2]
Hello, I need documentation so that I can use it. There is no documentation at all, which makes it entirely impossible to put this to good use as a new user of this library. Is it the case that it is identical to ProcessingJS or not?

**Comment by 99TheDark** [comment]
It is very similar to ProcessingJS, but as you might see by the latest release, it is still a pre-release. 

As the README.md file states, "Once this is done, I will probably make a Github Pages site with documentation & other miscellaneous things."

**Comment by dragon-ball6** [comment]
Ah, I see. Thank you! So does that mean that I can use it exactly like the original library?

**Comment by 99TheDark** [comment]
_Almost_ everything has been implemented, but just keep in mind this is in it's early stages (day 4)
